service: meusick-api-node
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-offline
  - serverless-express
  - serverless-wsgi
  - serverless-iam-roles-per-function

functions:
  hello:
    handler: handler.api
    events:
      - httpApi:
          path: /ex
          method: get
  s3file:
    handler: handlerS3.hello
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - 's3:ListBucket'
        Resource: "arn:aws:s3:::meusick-bucket"

      - Effect: 'Allow'
        Action:
          - 's3:GetObject'
        Resource: "arn:aws:s3:::meusick-bucket"

      - Effect: 'Allow'
        Action:
          - 's3:ListObjects'
        Resource: "arn:aws:s3:::meusick-bucket"
    events:
      - httpApi:
          path: /s3file
          method: get
  heller:
    runtime: python3.8
    handler: handler_py.heller
    events:
      - httpApi:
          path: /heller
          method: get